service: ui-service
frameworkVersion: "4.7.0"

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2  # 리전 고정
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:ListBucket 
      Resource: "arn:aws:s3:::${env:CHAPTER2_BUCKET}/*"
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
      Resource: "arn:aws:sqs:*:*:${env:CHAPTER2_CRAWLERQUEUE}"
    - Effect: Allow
      Action:
        - sqs:ListQueues
      Resource: "arn:aws:sqs:::*"

functions:
  analyzeUrl:
    handler: handler.analyzeUrl
    environment:
      BUCKET: ${env:CHAPTER2_BUCKET}
      QUEUE: ${env:CHAPTER2_CRAWLERQUEUE}
      REGION: ${env:AWS_DEFAULT_REGION, 'ap-northeast-2'}
      ACCOUNTID: ${env:AWS_ACCOUNT_ID}
    events:
      - http:
          path: url/analyze
          method: post
          cors: true

  listUrls:
    handler: handler.listUrls
    environment:
      BUCKET: ${env:CHAPTER2_BUCKET}
    events:
      - http:
          path: url/list
          method: get
          cors: true

  listImages:
    handler: handler.listImages
    environment:
      BUCKET: ${env:CHAPTER2_BUCKET}
    events:
      - http:
          path: image/list
          method: get
          cors: true